version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: reservation-trips
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=reservation
      - POSTGRES_DB=prisma
